import type {
  AdminBriefingSpec,
  BriefingKpiSpec,
  BriefingSectionSpec,
  DashboardScope,
  ReviewFrequency,
} from "@/types/adminBriefing";

function kpi(
  code: string,
  name: string,
  scope: DashboardScope,
  sectionId: string,
  formula: string,
  green: string,
  yellow: string,
  red: string,
  frequency: ReviewFrequency,
  source: string,
  notes?: string,
): BriefingKpiSpec {
  return {
    code,
    name,
    scope,
    sectionId,
    formula,
    thresholds: { green, yellow, red },
    frequency,
    source,
    notes,
  };
}

function section(
  id: string,
  scope: DashboardScope,
  kind: "MODULE" | "BLOCK",
  title: string,
  description: string,
  kpis: BriefingKpiSpec[],
): BriefingSectionSpec {
  return { id, scope, kind, title, description, kpis };
}

export const GLX_ADMIN_BRIEFING_SPEC: AdminBriefingSpec = {
  objective:
    "Dar ao CEO e socios visibilidade clara e em tempo real sobre o presente da operacao e o futuro de crescimento da GLX Partners, sem misturar domínios.",
  primaryUser:
    "CEO e socios da GLX Partners, com revisao semanal de 30 minutos e revisao mensal de 60 minutos.",
  whyTwoViews:
    "Pipeline mede o futuro proximo e deve responder se o crescimento dos proximos 30-60 dias esta garantido. Operacao mede o presente e o passado recente e deve responder se a empresa esta saudavel hoje.",
  integrations: [
    {
      id: "pipedrive",
      name: "Pipedrive (CRM)",
      dataFed: [
        "Leads",
        "Leads quentes",
        "Calls realizadas",
        "Propostas",
        "Contratos fechados",
        "Pipeline ponderado",
        "Ciclo de vendas",
        "ACV",
        "Origem do lead",
        "Tipo de produto",
      ],
      integrationType: "API REST nativa com webhook a cada mudanca de etapa do funil",
      cadence: "Tempo real",
    },
    {
      id: "asaas",
      name: "ASAAS (financeiro)",
      dataFed: [
        "Receita total mensal",
        "Inadimplencia",
        "Fluxo de caixa projetado",
        "Faturas vencidas",
        "Recebimentos previstos",
      ],
      integrationType: "API REST ASAAS com pull diario automatizado via Make",
      cadence: "Diaria",
    },
    {
      id: "google-calendar",
      name: "Google Calendar",
      dataFed: [
        "Calls de qualificacao",
        "Calls de fechamento",
        "Diagnosticos OS",
        "Reunioes semanais com clientes",
      ],
      integrationType: "Google Calendar API com contagem de eventos por label/tag",
      cadence: "Diaria",
    },
    {
      id: "google-forms",
      name: "Google Forms",
      dataFed: ["NPS de clientes GLX", "Engajamento nas reunioes"],
      integrationType: "Google Forms conectado ao Google Sheets com pull semanal via Make",
      cadence: "Semanal",
    },
    {
      id: "contracts-sheet",
      name: "Planilha de Contratos (Google Sheets)",
      dataFed: [
        "Clientes ativos",
        "MRR por cliente",
        "Churn",
        "Tipo de plano",
        "Data de inicio",
        "Setups em andamento",
        "Status MRR 12m",
        "Status Advisory",
      ],
      integrationType: "Google Sheets API com atualizacao manual semanal pelo CEO e leitura automatica",
      cadence: "Semanal",
    },
    {
      id: "dre-sheet",
      name: "Planilha DRE (Google Sheets)",
      dataFed: ["Margem liquida", "Receita total", "Custos operacionais", "CAC", "Receita por hora trabalhada"],
      integrationType: "Google Sheets API com atualizacao manual mensal",
      cadence: "Mensal",
    },
    {
      id: "time-control",
      name: "Controle de Tempo (Notion/Planilha)",
      dataFed: ["Horas por cliente por semana", "Horas totais de operacao", "Receita por hora trabalhada"],
      integrationType: "Exportacao manual mensal ou integracao via Notion API",
      cadence: "Mensal",
    },
  ],
  views: [
    {
      id: "OPERATION",
      title: "Operacao Interna",
      questionAnswered: "A empresa esta saudavel agora?",
      timeHorizon: "Presente e passado recente",
      reviewCadence: "Semanal para indicadores criticos e mensal para resultado completo",
      products: ["Operation System (OS) - Start e Pro", "Advisory - Board e Scale"],
      funnelOs: [
        "Lead",
        "Lead Quente",
        "Call Qualificacao",
        "Call Fechamento",
        "Diagnostico",
        "Setup 60 dias",
        "MRR 12 meses",
      ],
      funnelAdvisory: [
        "Lead",
        "Lead Quente",
        "Call Qualificacao",
        "Call Fechamento",
        "MRR 6 meses",
      ],
      sections: [
        section(
          "receita-mrr",
          "OPERATION",
          "MODULE",
          "Modulo 1 - Receita & MRR",
          "Saude de receita recorrente, previsibilidade e impacto de cancelamento.",
          [
            kpi("OP-M1-01", "MRR Total (R$)", "OPERATION", "receita-mrr", "Soma do valor do plano x clientes ativos no mes.", "Crescente todo mes", "Crescimento abaixo de 8% ao mes", "MRR estagnado ou caindo por 2 meses", "MONTHLY", "Planilha Contratos"),
            kpi("OP-M1-02", "Crescimento MRR (%)", "OPERATION", "receita-mrr", "(MRR mes atual - MRR mes anterior) / MRR mes anterior x 100", "> 15% ao mes", "8% - 15% ao mes", "< 8% por 2 meses consecutivos", "MONTHLY", "Calculado"),
            kpi("OP-M1-03", "New MRR (R$)", "OPERATION", "receita-mrr", "Soma do MRR de contratos novos assinados no mes: OS Start + OS Pro + Advisory Board + Advisory Scale.", "Maior ou igual a meta mensal definida no setup", "50% - 99% da meta", "Zero new MRR no mes", "MONTHLY", "Pipedrive + Contratos"),
            kpi("OP-M1-04", "Churn MRR (R$)", "OPERATION", "receita-mrr", "Soma do MRR de clientes que cancelaram ou reduziram plano no mes.", "< 5% do MRR total", "5% - 10% do MRR", "> 10% do MRR no mes", "MONTHLY", "Planilha Contratos"),
            kpi("OP-M1-05", "Forecast MRR - 3 meses (R$)", "OPERATION", "receita-mrr", "Pipeline ponderado + contratos ja assinados e vigentes.", "Desvio de no maximo 15% do realizado", "Desvio de 15% - 30%", "Forecast abaixo de 70% da meta do proximo mes", "WEEKLY", "Pipedrive"),
          ],
        ),
        section(
          "clientes-retencao",
          "OPERATION",
          "MODULE",
          "Modulo 2 - Clientes & Retencao",
          "Saude da base ativa, retenção, experiencia e indicacao.",
          [
            kpi("OP-M2-01", "Clientes Ativos (n)", "OPERATION", "clientes-retencao", "Total de clientes com contrato recorrente ativo no ultimo dia do mes.", "Crescente todo mes", "Estavel sem crescimento por 2 meses", "Queda no total de clientes ativos", "MONTHLY", "Planilha Contratos"),
            kpi("OP-M2-02", "Churn Rate (%)", "OPERATION", "clientes-retencao", "Clientes que cancelaram no mes / total de clientes no inicio do mes x 100", "< 3% ao mes", "3% - 7%", "> 7% em 1 mes", "MONTHLY", "Planilha Contratos", "RCA obrigatoria acima do vermelho."),
            kpi("OP-M2-03", "NPS de Clientes GLX (0-10)", "OPERATION", "clientes-retencao", "Media das notas coletadas via formulario mensal com a pergunta de recomendacao.", "> 8.5", "7.5 - 8.5", "< 7.5", "MONTHLY", "Google Forms", "Reuniao imediata com detratores abaixo do vermelho."),
            kpi("OP-M2-04", "Entregas no Prazo (%)", "OPERATION", "clientes-retencao", "Entregas realizadas no prazo / total de entregas previstas no mes x 100", "> 95%", "85% - 95%", "< 85%", "WEEKLY", "Checklist por cliente", "Abaixo do vermelho implica gargalo operacional interno."),
            kpi("OP-M2-05", "Tempo Medio de Onboarding (dias)", "OPERATION", "clientes-retencao", "Dias entre assinatura do contrato e primeira reuniao realizada.", "< 15 dias", "15 - 25 dias", "> 25 dias", "MONTHLY", "Planilha Projetos", "Acima do vermelho indica processo com gargalo."),
            kpi("OP-M2-06", "Health Score por Cliente (0-10)", "OPERATION", "clientes-retencao", "NPS 40% + entregas no prazo 30% + adimplencia 20% + engajamento nas reunioes 10%", "Todos os clientes > 7.0", "Qualquer cliente entre 5.0 e 7.0", "Qualquer cliente < 5.0", "MONTHLY", "Calculado (Forms + Checklist)", "Abaixo de 5.0 exige plano de resgate."),
            kpi("OP-M2-07", "Taxa de Indicacao (%)", "OPERATION", "clientes-retencao", "Leads novos originados por indicacao direta de clientes GLX / total de leads novos no mes x 100", "> 30%", "15% - 30%", "< 15%", "MONTHLY", "Pipedrive (campo origem)", "Abaixo do vermelho indica clientes nao recomendando."),
          ],
        ),
        section(
          "financeiro-interno",
          "OPERATION",
          "MODULE",
          "Modulo 3 - Financeiro Interno",
          "Receita total, margem, CAC, caixa e eficiencia financeira.",
          [
            kpi("OP-M3-01", "Receita Total Mensal (R$)", "OPERATION", "financeiro-interno", "MRR + receitas one-time faturadas no mes.", "Maior ou igual a meta do mes", "80% - 99% da meta no dia 20", "< 80% da meta no dia 20", "MONTHLY", "ASAAS + DRE"),
            kpi("OP-M3-02", "Margem Liquida (%)", "OPERATION", "financeiro-interno", "(Receita Total - todos os custos operacionais) / Receita Total x 100", "> 35%", "20% - 35%", "< 20%", "MONTHLY", "Planilha DRE", "Abaixo do vermelho exige auditoria imediata de custos."),
            kpi("OP-M3-03", "CAC (R$)", "OPERATION", "financeiro-interno", "Gasto total em marketing + vendas no mes / numero de novos clientes fechados no mes", "< 3x MRR medio do plano vendido", "3x - 6x MRR medio", "> 6x MRR medio", "MONTHLY", "DRE + Pipedrive", "Aquisicao fica insustentavel no vermelho."),
            kpi("OP-M3-04", "Fluxo de Caixa Projetado (R$)", "OPERATION", "financeiro-interno", "Saldo atual + recebimentos confirmados dos proximos 60 dias - despesas fixas e variaveis previstas", "Positivo e crescente", "Positivo mas com menos de 1 mes de reserva", "Negativo em qualquer mes projetado", "WEEKLY", "ASAAS + Planilha"),
            kpi("OP-M3-05", "Inadimplencia (%)", "OPERATION", "financeiro-interno", "Faturas vencidas ha mais de 15 dias e nao pagas / Receita Total do mes x 100", "< 3%", "3% - 8%", "> 8%", "WEEKLY", "ASAAS", "Acima do vermelho exige cobranca urgente."),
            kpi("OP-M3-06", "Receita por Hora (R$/h)", "OPERATION", "financeiro-interno", "Receita Total do mes / total de horas na operacao (entrega + reunioes + vendas + gestao interna)", "> R$300/h", "R$150 - R$300/h", "< R$150/h", "MONTHLY", "DRE + Controle de Tempo", "Abaixo do vermelho indica operacao ineficiente."),
          ],
        ),
        section(
          "capacidade-operacao",
          "OPERATION",
          "MODULE",
          "Modulo 4 - Capacidade & Operacao",
          "Uso da capacidade, tempo por cliente e SLA de resposta.",
          [
            kpi("OP-M4-01", "Utilizacao de Capacidade (%)", "OPERATION", "capacidade-operacao", "Clientes ativos / capacidade maxima do modelo atual x 100", "70% - 85%", "85% - 95%", "> 95%", "WEEKLY", "Planilha Capacidade", "Acima do vermelho nao aceitar novo cliente sem contratar."),
            kpi("OP-M4-02", "Horas por Cliente / Semana", "OPERATION", "capacidade-operacao", "Total horas de entrega + reuniao + gestao do mes / numero de clientes ativos / 4 semanas", "< 4h por cliente por semana", "4h - 6h por cliente por semana", "> 6h por cliente por semana", "WEEKLY", "Controle de Tempo", "Acima do vermelho indica entrega nao padronizada."),
            kpi("OP-M4-03", "SLA Resposta Clientes (horas)", "OPERATION", "capacidade-operacao", "Tempo medio entre mensagem do cliente e resposta da GLX em horario util", "< 2 horas", "2h - 6h", "> 8h", "WEEKLY", "WhatsApp / Gmail", "Acima do vermelho coloca a experiencia do cliente em risco."),
          ],
        ),
      ],
    },
    {
      id: "PIPELINE",
      title: "Pipeline & Funil",
      questionAnswered: "O crescimento futuro esta garantido?",
      timeHorizon: "Futuro proximo de 30-60 dias",
      reviewCadence: "Semanal e, quando prospectando ativamente, diario",
      products: ["Operation System (OS) - Start e Pro", "Advisory - Board e Scale"],
      funnelOs: [
        "Lead",
        "Lead Quente",
        "Call Qualificacao",
        "Call Fechamento",
        "Diagnostico",
        "Setup 60 dias",
        "MRR 12 meses",
      ],
      funnelAdvisory: [
        "Lead",
        "Lead Quente",
        "Call Qualificacao",
        "Call Fechamento",
        "MRR 6 meses",
      ],
      sections: [
        section(
          "topo-funil",
          "PIPELINE",
          "BLOCK",
          "Bloco 1 - Topo do Funil",
          "Entrada de leads, aquecimento e passagem para call.",
          [
            kpi("PI-B1-01", "Leads Totais Gerados", "PIPELINE", "topo-funil", "Numero total de leads que entraram em contato ou foram prospectados no periodo por todos os canais.", "> 40 por mes", "20 - 40 por mes", "< 20 por mes", "WEEKLY", "Pipedrive / LinkedIn", "Abaixo do vermelho por 2 meses seguidos."),
            kpi("PI-B1-02", "Leads Quentes", "PIPELINE", "topo-funil", "Leads com interesse claro movidos para a etapa de qualificacao.", "> 15 por mes", "8 - 15 por mes", "< 8 por mes", "WEEKLY", "Pipedrive"),
            kpi("PI-B1-03", "Taxa Lead -> Lead Quente (%)", "PIPELINE", "topo-funil", "Leads Quentes / Leads Totais x 100", "> 35%", "20% - 35%", "< 20%", "WEEKLY", "Calculado - Pipedrive", "Vermelho indica mensagem ou canal sem gerar interesse."),
            kpi("PI-B1-04", "Calls de Qualificacao", "PIPELINE", "topo-funil", "Numero de calls de qualificacao efetivamente realizadas no periodo.", "> 10 por mes", "5 - 10 por mes", "< 5 por mes", "WEEKLY", "Pipedrive / Google Calendar"),
            kpi("PI-B1-05", "Taxa Lead Quente -> Call (%)", "PIPELINE", "topo-funil", "Calls de qualificacao realizadas / Leads Quentes x 100", "> 60%", "40% - 60%", "< 40%", "WEEKLY", "Calculado - Pipedrive", "Vermelho indica leads esfriando antes da call."),
          ],
        ),
        section(
          "fechamento",
          "PIPELINE",
          "BLOCK",
          "Bloco 2 - Fechamento",
          "Aquecimento comercial, calls de fechamento e conversao para contrato.",
          [
            kpi("PI-B2-01", "Calls de Fechamento", "PIPELINE", "fechamento", "Numero de calls de fechamento com proposta apresentada.", "> 6 por mes", "3 - 6 por mes", "< 3 por mes", "WEEKLY", "Pipedrive / Google Calendar"),
            kpi("PI-B2-02", "Taxa Qualif. -> Fechamento (%)", "PIPELINE", "fechamento", "Calls de fechamento / Calls de qualificacao x 100", "> 70%", "50% - 70%", "< 50%", "MONTHLY", "Calculado - Pipedrive", "Vermelho indica lead nao esta sendo aquecido."),
            kpi("PI-B2-03", "Taxa Fechamento -> Contrato (%)", "PIPELINE", "fechamento", "Contratos assinados (OS + Advisory) / Calls de fechamento x 100", "> 40%", "25% - 40%", "< 25%", "MONTHLY", "Calculado - Pipedrive", "Vermelho indica problema de proposta ou preco."),
            kpi("PI-B2-04", "Ciclo Medio Lead -> Contrato (dias)", "PIPELINE", "fechamento", "Media de dias entre primeiro contato com o lead e assinatura do contrato.", "< 21 dias", "21 - 45 dias", "> 45 dias", "MONTHLY", "Pipedrive (datas por etapa)", "Calcular separado OS vs Advisory."),
          ],
        ),
        section(
          "operation-system",
          "PIPELINE",
          "BLOCK",
          "Bloco 3 - Operation System (OS)",
          "Pipeline especifico do produto OS, com diagnostico, setup e recorrencia.",
          [
            kpi("PI-B3-01", "Diagnosticos Agendados OS", "PIPELINE", "operation-system", "Numero de reunioes de diagnostico confirmadas com clientes OS no periodo.", "> 4 por mes", "2 - 4 por mes", "< 2 por mes", "WEEKLY", "Google Calendar / Pipedrive"),
            kpi("PI-B3-02", "Setups Fechados OS", "PIPELINE", "operation-system", "Contratos de Setup assinados apos diagnostico no periodo, separados entre Start e Pro.", "> 3 por mes", "1 - 3 por mes", "0 setups no mes", "MONTHLY", "Contratos - Pipedrive", "No vermelho significa que diagnosticos nao convertem."),
            kpi("PI-B3-03", "Taxa Diagnostico -> Setup (%)", "PIPELINE", "operation-system", "Setups fechados / diagnosticos realizados x 100", "> 70%", "50% - 70%", "< 50%", "MONTHLY", "Calculado - Pipedrive", "Vermelho indica diagnostico nao convence."),
            kpi("PI-B3-04", "Taxa Setup -> MRR 12m (%)", "PIPELINE", "operation-system", "MRR 12m assinados / setups concluidos (60 dias) x 100", "> 80%", "60% - 80%", "< 60%", "MONTHLY", "Calculado - Contratos", "Metrica mais importante do produto OS."),
            kpi("PI-B3-05", "OS Start Ativos % MRR 12m", "PIPELINE", "operation-system", "Clientes OS Start em MRR 12m / total de clientes OS Start ativos x 100", "> 80%", "60% - 80%", "< 60%", "MONTHLY", "Planilha Contratos", "No vermelho o produto Start nao converte em recorrente."),
            kpi("PI-B3-06", "OS Pro Ativos % MRR 12m", "PIPELINE", "operation-system", "Clientes OS Pro em MRR 12m / total de clientes OS Pro ativos x 100", "> 80%", "60% - 80%", "< 60%", "MONTHLY", "Planilha Contratos", "No vermelho o produto Pro nao converte em recorrente."),
          ],
        ),
        section(
          "advisory",
          "PIPELINE",
          "BLOCK",
          "Bloco 4 - Advisory",
          "Pipeline especifico do Advisory, sem diagnostico nem setup.",
          [
            kpi("PI-B4-01", "Advisory Fechados", "PIPELINE", "advisory", "Contratos Advisory assinados diretamente apos call de fechamento.", "> 2 por mes", "1 por mes", "0 no mes", "MONTHLY", "Contratos - Pipedrive", "Advisory nao possui diagnostico nem setup."),
            kpi("PI-B4-02", "Advisory Ativos Total", "PIPELINE", "advisory", "Total de clientes ativos em qualquer plano Advisory (Board + Scale).", "Crescente", "Estavel por 2 meses", "Queda no total", "MONTHLY", "Planilha Contratos"),
            kpi("PI-B4-03", "Taxa Renovacao Advisory 6m (%)", "PIPELINE", "advisory", "Contratos Advisory renovados / contratos Advisory vencidos no periodo x 100", "> 75%", "50% - 75%", "< 50%", "MONTHLY", "Contratos - Pipedrive", "No vermelho o produto Advisory esta sem valor claro."),
          ],
        ),
        section(
          "consolidada",
          "PIPELINE",
          "BLOCK",
          "Bloco 5 - Visao Consolidada",
          "Pipeline ponderado, ACV e setups em andamento para leitura executiva.",
          [
            kpi("PI-B5-01", "Pipeline Ponderado Total (R$)", "PIPELINE", "consolidada", "Soma de valor do contrato x probabilidade por etapa. Probabilidades sugeridas: Lead Quente 10%, Call Qualif. 30%, Call Fech. 60%, Proposta enviada 80%.", "> 3x meta MRR do mes", "2x - 3x meta", "< 2x meta", "WEEKLY", "Pipedrive", "Risco de nao bater a meta do mes no vermelho."),
            kpi("PI-B5-02", "ACV - Valor Medio Contrato (R$)", "PIPELINE", "consolidada", "Receita de novos contratos assinados / numero de novos contratos", "Estavel ou crescente", "Queda < 15% vs mes anterior", "Queda > 15% por 2 meses", "MONTHLY", "Pipedrive + Contratos", "Monitorar OS vs Advisory para entender mix de receita."),
            kpi("PI-B5-03", "Setups em Andamento (n)", "PIPELINE", "consolidada", "Clientes OS atualmente dentro dos 60 dias de Setup.", "> 2 simultaneos", "1 em andamento", "0 por 2 meses seguidos", "WEEKLY", "Planilha Projetos"),
          ],
        ),
      ],
    },
  ],
  alerts: [
    {
      status: "GREEN",
      trigger: "KPI dentro ou acima da meta definida",
      requiredAction: "Nenhuma acao; manter o que esta funcionando e registrar alavancas replicaveis",
      deadline: "Sem prazo emergencial",
    },
    {
      status: "YELLOW",
      trigger: "KPI entre o threshold de atencao e a meta ou tendencia negativa ainda nao critica",
      requiredAction: "Investigar a causa raiz e incluir o item na proxima reuniao semanal",
      deadline: "Proximos 7 dias, monitorando por 2 ciclos antes de escalar",
    },
    {
      status: "RED",
      trigger: "KPI abaixo do threshold critico ou tendencia negativa por 2 semanas ou mais",
      requiredAction: "Acao imediata com RCA obrigatoria, decisao documentada, responsavel e prazo definidos",
      deadline: "24 horas",
    },
  ],
  cadence: {
    daily: ["Fluxo de caixa", "Alertas vermelhos abertos", "SLA de resposta"],
    weekly: ["Pipeline ponderado", "Leads", "Calls", "Entregas no prazo", "Utilizacao de capacidade", "Forecast"],
    monthly: ["MRR", "Churn", "CAC", "Margem", "NPS", "Health Score", "Taxa de indicacao", "Receita por hora"],
  },
  deliveryPriority: [
    {
      phase: 1,
      title: "Visao 2 - Pipeline & Funil completo",
      includes: ["Blocos 1 a 5", "Integracoes Pipedrive", "Google Calendar", "Planilha de Contratos"],
      suggestedWindow: "Semana 1-2",
    },
    {
      phase: 2,
      title: "Visao 1 - Operacao: MRR + Clientes + Financeiro",
      includes: ["Modulos 1, 2 e 3", "Integracoes ASAAS", "Google Forms", "Planilha Contratos", "DRE"],
      suggestedWindow: "Semana 3-4",
    },
    {
      phase: 3,
      title: "Visao 1 - Capacidade + Scorecard Executivo",
      includes: ["Modulo 4", "Scorecard consolidado com 21 KPIs de operacao"],
      suggestedWindow: "Semana 5",
    },
    {
      phase: 4,
      title: "Alertas automaticos e polish visual",
      includes: ["Sistema de semaforo automatico", "Notificacoes push para alertas vermelhos", "UX final"],
      suggestedWindow: "Semana 6",
    },
  ],
  layoutMapping: [
    {
      route: "/admin/pipeline",
      topPanel: "Visao executiva do pipeline com 6 KPI cards e linhas principais de graficos",
      bottomPanel: "Tabela de oportunidades, gargalos, alertas do pipeline e drilldown comercial",
    },
    {
      route: "/admin/operacao",
      topPanel: "Visao executiva da operacao com 6 KPI cards e graficos principais",
      bottomPanel: "Health score por cliente, inadimplencia, gargalos de onboarding, atrasos e alertas operacionais",
    },
    {
      route: "/admin/erros-logs",
      topPanel: "Status geral de integracoes, jobs e severidade",
      bottomPanel: "Tabela de logs, sync runs, RCA e historico de falhas",
    },
    {
      route: "/admin/integracoes/*",
      topPanel: "Status da conexao, ultima sync, volume, falhas recentes e latencia",
      bottomPanel: "Historico de sync, mapeamento de campos, erros recentes e botao de resync",
    },
  ],
};
